# on:
#   schedule:
#     - cron: '0 0 * * *' # every 24 hours at midnight
on:
  push:
    branches:
      - 'astone123/ct-automated-tests'

jobs:
  cra-latest:
    name: Create React App Latest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-cra5-ts/
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          yarn
      - name: Upgrade react-scripts to latest version
        run: |
          yarn upgrade react-scripts --latest
          yarn list --pattern react-scripts
      - name: Run component tests
        run: |
          yarn cypress run --component